# docker-compose.yml

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-auth
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: bitnami/redis:latest
    container_name: redis-container
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - '6379:6379'
volumes:
  postgres:
  redis:
